apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: web-app1
  name: web-app1
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: web-app1
  template:
    metadata:
      labels:
        k8s-app: web-app1
    spec:
      initContainers:
      - name: busybox
        image: busybox:latest
        command: ["/bin/sh"]
        args:
        - -c
        - "echo '<html><center>Web Application - 1</center></html>' > /tmp/data/index.html"
        volumeMounts:
        - name: datadir
          mountPath:  /tmp/data
      containers:
      - name: nginx
        image: nginx:1.7.9
        volumeMounts:
        - name: datadir
          mountPath: "/usr/share/nginx/html"
          #subPath: "index.html" 
          readOnly: yes
      volumes:
      - name: datadir
        emptyDir: {}
